version: 2

models:
  - name: rsi
    description: "Analytics model for session data"
    columns:
      - name: date
        description: "Unique identifier for each stock price record"
        data_tests:
          - unique
          - not_null
  - name: moving_avg_7d
    description: "Analytics model for session data"
    columns:
      - name: date
        description: "Unique identifier for each stock price record"
        data_tests:
          - unique
          - not_null
  - name: price_momentum
    description: "Analytics model for session data"
    columns:
      - name: date
        description: "Unique identifier for each stock price record"
        data_tests:
          - unique
          - not_null
  - name: stock_summary
    description: "Analytics model for session data"
    columns:
      - name: date
        description: "Unique identifier for each stock price record"
        data_tests:
          - unique
          - not_null
        
