version: 2

models:
  - name: rsi_values
    description: "Analytics model for session data"
    columns:
      - name: date
        description: "Unique identifier for each stock price record"
        data_tests:
          - unique
          - not_null
        
